name: Sync Events from Google Sheets

on:
  # Run when manually triggered
  workflow_dispatch:
  
  # Run on a schedule (every hour)
  schedule:
    - cron: '0 * * * *'  # Every hour
  
  # Run when webhook is triggered
  repository_dispatch:
    types: [sync-events]

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fetch events from Google Sheets API
        id: fetch
        run: |
          # Call the Vercel API endpoint to get synced data
          RESPONSE=$(curl -s "https://aliyafinancial.com/api/sync-events")
          echo "$RESPONSE" > sync-response.json
          
          # Extract the JSON data
          PUBLIC_JSON=$(echo "$RESPONSE" | jq -c '.publicJSON')
          PRIVATE_JSON=$(echo "$RESPONSE" | jq -c '.privateJSON')
          
          # Write to files
          echo "$PUBLIC_JSON" | jq '.' > public-events.json
          echo "$PRIVATE_JSON" | jq '.' > private-events.json
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add public-events.json private-events.json
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-sync events from Google Sheets [skip ci]"
            git push
          fi
